[package]
name = "write_summary"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
serde_json = "1.0.83"
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
iox_time = { path = "../iox_time" }
