[package]
name = "iox_data_generator"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2021"
default-run = "iox_data_generator"

[dependencies]
chrono = { version = "0.4", default-features = false }
chrono-english = "0.1.4"
clap = { version = "3", features = ["derive", "env", "cargo"] }
futures = "0.3"
handlebars = "4.3.3"
humantime = "2.1.0"
influxdb2_client = { path = "../influxdb2_client" }
itertools = "0.10.0"
rand = { version = "0.8.3", features = ["small_rng"] }
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.83"
snafu = "0.7"
tokio = { version = "1.20", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
toml = "0.5.9"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", default_features = false }

[dev-dependencies]
criterion = "0.3.6"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "point_generation"
harness = false
