[package]
name = "metric"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"

[dependencies] # In alphabetical order
parking_lot = "0.12"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
