version: "3.9"
services:
  redpanda:
    pull_policy: always
    image: docker.vectorized.io/vectorized/redpanda:latest
    ports:
      - 9092:9092
      - 9644:9644
    command: start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
  postgres:
    pull_policy: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

# To use this file with the integration tests, see docs/testing.md
