[package]
name = "write_buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
dotenvy = "0.15.1"
futures = "0.3"
generated_types = { path = "../generated_types" }
hashbrown = "0.12"
http = "0.2"
httparse = "1.7"
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pin-project = "1.0"
prost = "0.10"
rskafka = { git = "https://github.com/influxdata/rskafka.git", rev="e34f6f485db9256a7614220cabea86f7c44f5eb6", default-features = false, features = ["compression-snappy", "transport-socks5"] }
schema = { path = "../schema" }
tokio = { version = "1.20", features = ["fs", "macros", "parking_lot", "rt", "sync", "time"] }
tokio-util = "0.7.3"
trace = { path = "../trace" }
trace_http = { path = "../trace_http" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers" }

[package.metadata.cargo-udeps.ignore]
# used within the `maybe_skip_kafka_integration` macro and cannot be detected by a normal analysis pass
normal = ["dotenvy"]
