[package]
name = "ingester"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"

[dependencies]
arrow = { version = "19.0.0", features = ["prettyprint"] }
arrow-flight = "19.0.0"
arrow_util = { path = "../arrow_util" }
async-trait = "0.1.57"
backoff = { path = "../backoff" }
bytes = "1.2"
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
data_types = { path = "../data_types" }
flatbuffers = "2.1.2"
futures = "0.3"
generated_types = { path = "../generated_types" }
chrono = { version = "0.4", default-features = false }
dml = { path = "../dml" }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch"}
mutable_batch_lp = { path = "../mutable_batch_lp" }
object_store = "0.3.0"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
pin-project = "1.0"
predicate = { path = "../predicate" }
prost = "0.10"
iox_query = { path = "../iox_query" }
schema = { path = "../schema" }
snafu = "0.7"
thiserror = "1.0"
iox_time = { path = "../iox_time" }
tokio = { version = "1.20", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tonic = { version = "0.7" }
tracker = { path = "../tracker" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}
write_buffer = { path = "../write_buffer" }
write_summary = { path = "../write_summary" }
tokio-util = { version = "0.7.3" }
trace = { path = "../trace" }

[dev-dependencies]
assert_matches = "1.5.0"
bitflags = {version = "1.3.2"}
once_cell = "1"
paste = "1.0.8"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio-stream = {version = "0.1.9", default_features = false }
