[package]
name = "metric_exporters"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"

[dependencies] # In alphabetical order

observability_deps = { path = "../observability_deps" }
metric = { path = "../metric" }
prometheus = { version = "0.13", default-features = false }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
