[package]
name = "trace_exporters"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"
description = "Additional tracing exporters for IOx"

[dependencies]

async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "3", features = ["derive", "env"] }
futures = "0.3"
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
thrift = { version = "0.13.0" }
tokio = { version = "1.20", features = ["macros", "parking_lot", "rt", "sync"] }
trace = { path = "../trace" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
