[package]
name = "cache_system"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
futures = "0.3"
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pdatastructs = { version = "0.7", default-features = false, features = ["fixedbitset"] }
tokio = { version = "1.20", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
trace = { path = "../trace"}
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
criterion = "0.3"
proptest = { version = "1", default_features = false, features = ["std"] }
rand = "0.8.3"

[[bench]]
name = "addressable_heap"
harness = false
