[package]
name = "service_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
datafusion = { path = "../datafusion" }
predicate = { path = "../predicate" }
iox_query = { path = "../iox_query" }
metric = { path = "../metric" }
parking_lot = "0.12"
trace = { path = "../trace" }
tracker = { path = "../tracker" }
workspace-hack = { path = "../workspace-hack"}

# Crates.io dependencies, in alphabetical order
async-trait = "0.1.57"
