[package]
name = "panic_logging"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2021"

[dependencies] # In alphabetical order
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
workspace-hack = { path = "../workspace-hack"}
